### ISSUE TITLE
AMD GPU

### ISSUE THREAD

**Issue by aaronsace** [nicehash/nheqminer#31]
GPU mining not working: 

```
<info> found 2 devices
<info> compiling ...
<info> source: 0 bytes
<error> source files not found or empty
```

**Comment by Eyedol-X** [comment]
I get "Fail OCL" spam error message when attempting to use AMD GPU here

**Comment by aaronsace** [comment]
Me to, it says this just before the spam.

**Comment by Eyedol-X** [comment]
I got a capture right before it where it said no OpenCL GPU's detected

I'm using latest WHQL Drivers on Win 7 X64

**Comment by aaronsace** [comment]
Fixed it! Put a bat file in the same folder as 'nheqminer.exe'. Nicehash haven't set the working directory correctly.

**Comment by Eyedol-X** [comment]
@aaronsace -- can you elaborate on what the bat file contains? I have been using a bat file to launch mine from the beginning, Perhaps is the directory I'm using?

**Comment by aaronsace** [comment]
@Eyedol-X -- it needs to build a bin file per gpu. Put the files in 'c:\nheqminer' then put 'cd c:\nheqminer' on the first line of the bat. Call 'nheqminer.exe' without the full path.

**Comment by Eyedol-X** [comment]
My GPU is being detected as "(OCL_XMP) TODO" -- still fails with the batch and call using same directory you indicated
![ocl todo](https://cloud.githubusercontent.com/assets/22627805/19826258/9ba3f16c-9d4b-11e6-965a-6b310d26196c.JPG)

Batch File
```
cd c:\nheqminer
Call nheqminer.exe -l usa -u BTCADDRESS -od 0 1 2 3
```

**Comment by aaronsace** [comment]
Seems like it's not detecting your cards properly. You tried downloading the drivers from here?http://support.amd.com/en-us/download/desktop?os=Windows+7+-+64

**Comment by Eyedol-X** [comment]
looks like I got it working with my RX480's -- still working on my R9390 system, drivers were out of date.

Thanks!

**Comment by Eyedol-X** [comment]
Some more info: have to be careful to pay attention to the platform ID setting. On one of my systems I had to define -op as the default 0 was my iGPU on one of my systems.

**Comment by zenbooster** [comment]
AMD Radeon HD5450:

nheqminer_v0.3a_suprnova>nheqminer_suprnova -u zenbooster.censored -p censored -t 0 -od 0

        ==================== www.nicehash.com ====================
                Equihash CPU&GPU Miner for Suprnova v0.3a
        Thanks to Zcash developers for providing base of the code.
            Special thanks to tromp and xenoncat for providing
                 optimized CPU and CUDA equihash solvers.
        ==================== www.nicehash.com ====================

Setting log level to 2
[2016-10-29 08:52:20.788917][0x00001024]: Using SSE2: YES
[2016-10-29 08:52:20.798917][0x00001024]: Using AVX: NO
[2016-10-29 08:52:20.808917][0x00001024]: Using AVX2: NO
[2016-10-29 08:52:20.818917][0x00001a50]: stratum | Starting miner
[2016-10-29 08:52:20.828917][0x00001398]: miner#0 | Starting thread #0 (OCL_XMP) TODO
[2016-10-29 08:52:20.838917][0x00001a50]: stratum | Connecting to stratum server zec-eu.suprnova.cc:2142
[2016-10-29 08:52:21.008917][0x00001a50]: stratum | Connected!
[2016-10-29 08:52:21.068917][0x00001a50]: stratum | Subscribed to stratum server
[2016-10-29 08:52:21.078917][0x00001a50]: miner | Extranonce is c2b5010000000000000000000001b5c3
[2016-10-29 08:52:21.148918][0x00001a50]: stratum | ←[35mTarget set to 00f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0←[0m
[2016-10-29 08:52:21.168918][0x00001a50]: stratum | ←[36mReceived new job #183←[0m
<info> found 1 devices
Using device 0 as GPU 0
<info> compiling ...
<info> source: 41162 bytes
[2016-10-29 08:52:21.408918][0x00001a50]: stratum | Authorized worker zenbooster.censored
[2016-10-29 08:52:31.320932][0x00001024]: ←[33mSpeed [300 sec]: 0 I/s, 0 Sols/s←[0m
[2016-10-29 08:52:43.516950][0x00001024]: ←[33mSpeed [300 sec]: 0 I/s, 0 Sols/s←[0m
[2016-10-29 08:52:59.368972][0x00001024]: ←[33mSpeed [300 sec]: 0 I/s, 0 Sols/s←[0m
[2016-10-29 08:53:13.196992][0x00001024]: ←[33mSpeed [300 sec]: 0 I/s, 0 Sols/s←[0m

**Comment by runvnc** [comment]
Sorry if this is a dumb question but I have an R9 380 on Windows, single core CPU. I used the command line `nheqminer.exe -l usa -u 13cii8BfnKbZkGUQM2Qgz42zzdMo6fYk5d -t 2 -od 0`

How can I verify that I am actually using the GPU at all? When it started up things scrolled by fast but I was not sure it said anything about using the GPU.  It definitely mentioned the CPU, couldn't tell if it said anything about GPU.  Would it just error out if I said `od` and it couldn't find a GPU?

Thanks.

**Comment by zenbooster** [comment]
Try use  -t 0 -od 0

**Comment by runvnc** [comment]
@zenbooster thanks

**Comment by runvnc** [comment]
@zenbooster thanks, by turning off threads I was able to confirm it is GPU mining, but it seems to be going much faster with the CPU on also, so I put it back to the original command line.  But I believe AMD mining is working also (maybe not as much faster as CPU mining as I would have thought though -- I was looking at 5.5 I/s, 10.7 Sols/s on the GPU, now with CPU on also it changed to 12.2 I/s, 23.6 Sols/s (should have bought nVidia lol)).

**Comment by aaronsace** [comment]
GPU mining has much more potential; I hope they update it soon.

**Comment by Eyedol-X** [comment]
AMD GPU is not optimized at this time, only CUDA has been with 0.3a

**Comment by molitar** [comment]
Yeah why no new release yet! It's been 7 days!  We need an AMD GPU miner!

**Comment by aaronsace** [comment]
There is; just not optimized yet.

**Comment by dtawom** [comment]
I'm getting 0 Sols/sec with AMD GPU mining for on a  R7 260x .  I'm running with just the GPU switch and it is detecting the card properly at the beginning.  Mining with the cpu switch works fine, and the gpu switch works fine on my nvidia system.  Is there a certain version of the amd driver that must be installed for this to work?  The switches I'm using are nheqminer.exe -l stratum.zcash.nicehash.com:3357 -u mypublicaddress -t 0 -od 0  Attached is a screenshot of my no sols.
![mine1](https://cloud.githubusercontent.com/assets/23352016/20128889/2db635ec-a5f8-11e6-91e9-a8d1a56e3f11.jpg)
And another of my card detection.
![mine2](https://cloud.githubusercontent.com/assets/23352016/20128915/60f4ad80-a5f8-11e6-92b1-bb4d1950dc68.jpg)

**Comment by molitar** [comment]
If your using an older card like that you need to use the 15.12 drivers.

**Comment by dtawom** [comment]
Thanks molitar, I found somebody mention the 15.11 drivers for another miner and suspected as much.  I appreciate the confirmation though.  I wish they'd add something about this in the FAQ or the official nicehash getting started page.

**Comment by S74nk0** [comment]
AMD (OpenCL) solver are dropped from **nheqminer**.
Closing issue...
